//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.19 at 02:35:18 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.data.hcalendar.com/userconfiguration", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.hcalendar.data.xml.userconfiguration;

